# ping.yml
trigger:
- main  # or your preferred branch

pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest'

jobs:
- job: PingGoogle
  displayName: 'Ping Google.com 10 times'
  steps:
  - script: |
      echo "Pinging google.com 10 times..."
      ping -c 10 google.com  # Use 'ping -n 10' on Windows
    displayName: 'Ping google.com'
