# ping.yml
trigger:
- main  # or your preferred branch

pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest'

jobs:
- job: PingLoopbackAddress
  displayName: 'Ping Google.com 10 times'
  steps:
  - script: |
      echo "Pinging loopback address 10 times..."
      ping -c 10 127.0.0.1  # Use 'ping -n 10' on Windows
    displayName: 'Ping loopback address'
