trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Checkout your code
- checkout: self

# Step 2: Install Terraform manually
- script: |
    sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform -y
    terraform version
  displayName: 'Install Terraform'

# Step 3: Download the GCP service account key securely
- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'  # This should be uploaded in Azure DevOps > Pipelines > Library > Secure Files

# Step 4: Terraform Init
- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
    terraform init
  displayName: 'Terraform Init'

# Step 5: Terraform Plan
- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

# Step 6: Terraform Apply
- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
