trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '$(TF_VERSION)'

- checkout: self

- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'gcp-key.json'

- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
    terraform init
  displayName: 'Terraform Init'

- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(gcpKey.secureFilePath)
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
