name: Deploy via GCP Impersonation

on:
  push:
    branches: [ main ]

permissions:
  id-token: write       # 👈 REQUIRED for GCP OIDC
  contents: read        # 👈 Also needed for checkout

jobs:
  deploy:
    uses: ./.github/workflows/gcp-auth-reusable.yml

    with:
      workload_identity_provider: "projects/741169614600/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      service_account_email: "github-actions-deployer@apigee-test-0002-demo.iam.gserviceaccount.com"
      project_id: "apigee-test-0002-demo"
