# Reusable workflow for GCP auth with impersonation
name: GCP Auth Reusable Workflow

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account_email:
        required: true
        type: string
      project_id:
        required: true
        type: string
    secrets:
      gcp_credentials_json:
        required: true

jobs:
  gcp-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud using Workload Identity Federation
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account_email }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify GCP Auth
        run: |
          gcloud config set project ${{ inputs.project_id }}
          gcloud auth list
          gcloud projects get-iam-policy ${{ inputs.project_id }} --format=json
